# Generated by Django 4.2.1 on 2023-06-25 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fototeca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='updated',
        ),
        migrations.AlterField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='fotos'),
        ),
    ]
