# Generated by Django 4.2.1 on 2023-06-19 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recuerdos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caja',
            name='categorias',
        ),
        migrations.DeleteModel(
            name='CategoriaCaja',
        ),
    ]
